### PR TITLE
Fixes ArgumentError search scope

### PR DESCRIPTION
**Pull request by CV-Gate**

### CODE REVIEW

**Comment by LTe** [comment]
@CV-Gate Hi, thanks for you pull request. Can you describe problem with `search` scope?

**Comment by LTe** [comment]
@CV-Gate I see that this is related to https://github.com/LTe/acts-as-messageable/issues/62. I think this scope name should be configurable. Because there can be another gem that define `text_search` method. In this way, we come back to the starting point.

**Comment by CV-Gate** [comment]
Hello LTe, yes, configurable is a good option but at this moment it's colliding with Active Admin that is very widely used. I think that even being configurable it won't be a bad idea to change de default name.

**Comment by LTe** [comment]
Closed by https://github.com/LTe/acts-as-messageable/pull/96

**Pull request closed without merging**
